-- Your SQL goes here
ALTER TABLE brands DISABLE TRIGGER ALL;
ALTER TABLE games DISABLE TRIGGER ALL;
ALTER TABLE timelines DISABLE TRIGGER ALL;
ALTER TABLE listmaps DISABLE TRIGGER ALL;
ALTER TABLE reviews DISABLE TRIGGER ALL;